'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class HelpStrings
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("DiskImageTool.HelpStrings", GetType(HelpStrings).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This Is additional data found in the Boot Sector.
        '''
        '''Note: Data highlighted in green is the bootstrap code..
        '''</summary>
        Friend Shared ReadOnly Property BootSectorForm_Help_AdditionalData() As String
            Get
                Return ResourceManager.GetString("BootSectorForm_Help_AdditionalData", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Allowed Values:.
        '''</summary>
        Friend Shared ReadOnly Property BootSectorForm_Help_AllowedValues() As String
            Get
                Return ResourceManager.GetString("BootSectorForm_Help_AllowedValues", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Indicated to the BIOS that the sector is executable..
        '''</summary>
        Friend Shared ReadOnly Property BootSectorForm_Help_BootSectorSignature() As String
            Get
                Return ResourceManager.GetString("BootSectorForm_Help_BootSectorSignature", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Number of bytes in each physical sector
        '''
        '''Allowed Values: {0}
        '''
        '''Note: This value should be {1} for all floppy disks..
        '''</summary>
        Friend Shared ReadOnly Property BootSectorForm_Help_BytesPerSector() As String
            Get
                Return ResourceManager.GetString("BootSectorForm_Help_BytesPerSector", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The disk type detected based on the current values in the Boot Record.  Changing this will set the values in the boot record to those of the selected disk type..
        '''</summary>
        Friend Shared ReadOnly Property BootSectorForm_Help_DiskType() As String
            Get
                Return ResourceManager.GetString("BootSectorForm_Help_DiskType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Interrupt 13h drive number
        '''
        '''Allowed Values: {0}.
        '''</summary>
        Friend Shared ReadOnly Property BootSectorForm_Help_DriveNumber() As String
            Get
                Return ResourceManager.GetString("BootSectorForm_Help_DriveNumber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Extended Boot Signature
        '''
        '''Typical Values:
        '''28h\tVolume Serial Number is present
        '''29h\tVolume Serial Number, Volume Label, and File System ID are present.
        '''</summary>
        Friend Shared ReadOnly Property BootSectorForm_Help_ExtendedBootSignature() As String
            Get
                Return ResourceManager.GetString("BootSectorForm_Help_ExtendedBootSignature", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The File System ID is informational only
        '''
        '''Typical Values: {0}.
        '''</summary>
        Friend Shared ReadOnly Property BootSectorForm_Help_FileSystemType() As String
            Get
                Return ResourceManager.GetString("BootSectorForm_Help_FileSystemType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fixed Disk.
        '''</summary>
        Friend Shared ReadOnly Property BootSectorForm_Help_FixedDisk() As String
            Get
                Return ResourceManager.GetString("BootSectorForm_Help_FixedDisk", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Number of sectors preceeding the first sector of a partitioned volume
        '''
        '''Note: This value should be {0} for all floppy disks.
        '''</summary>
        Friend Shared ReadOnly Property BootSectorForm_Help_HiddenSectors() As String
            Get
                Return ResourceManager.GetString("BootSectorForm_Help_HiddenSectors", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This instruction indicates where the bootstrap code starts.
        '''
        '''Allowed Values: {0}.
        '''</summary>
        Friend Shared ReadOnly Property BootSectorForm_Help_JumpInstruction() As String
            Get
                Return ResourceManager.GetString("BootSectorForm_Help_JumpInstruction", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Media Descriptor.
        '''</summary>
        Friend Shared ReadOnly Property BootSectorForm_Help_MediaDescriptor() As String
            Get
                Return ResourceManager.GetString("BootSectorForm_Help_MediaDescriptor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Number of File Allocation Table (FAT) copies on the volume
        '''
        '''Allowed Values: Any non-zero value
        '''
        '''Note: This value should typically be set to {0}..
        '''</summary>
        Friend Shared ReadOnly Property BootSectorForm_Help_NumberOfFATs() As String
            Get
                Return ResourceManager.GetString("BootSectorForm_Help_NumberOfFATs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Number of physical heads (sides) on the disk.
        '''</summary>
        Friend Shared ReadOnly Property BootSectorForm_Help_NumberOfHeads() As String
            Get
                Return ResourceManager.GetString("BootSectorForm_Help_NumberOfHeads", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to OEM Name Identifier
        '''
        '''Can be set by a FAT implementation to any desired value
        '''
        '''Typically this is some indication of what system formatted the volume..
        '''</summary>
        Friend Shared ReadOnly Property BootSectorForm_Help_OEMName() As String
            Get
                Return ResourceManager.GetString("BootSectorForm_Help_OEMName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Number of reserved sectors in the reserved region of the volume starting at the first sector of the volume
        '''
        '''Allowed Values: Any non-zero value
        '''
        '''Note: This value should typically be set to {0}..
        '''</summary>
        Friend Shared ReadOnly Property BootSectorForm_Help_ReservedSectors() As String
            Get
                Return ResourceManager.GetString("BootSectorForm_Help_ReservedSectors", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Number of entries in the root directory
        '''
        '''Allowed Values: Value multiplied by {0} should be an even multiple of Bytes Per Sector.
        '''</summary>
        Friend Shared ReadOnly Property BootSectorForm_Help_RootDirectoryEntries() As String
            Get
                Return ResourceManager.GetString("BootSectorForm_Help_RootDirectoryEntries", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Total number of sectors in a FAT16 volume larger than {0} sectors
        '''
        '''Note: This value should be {1} for all floppy disks.
        '''</summary>
        Friend Shared ReadOnly Property BootSectorForm_Help_SectorCountLarge() As String
            Get
                Return ResourceManager.GetString("BootSectorForm_Help_SectorCountLarge", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Total number of sectors in the volume.
        '''</summary>
        Friend Shared ReadOnly Property BootSectorForm_Help_SectorCountSmall() As String
            Get
                Return ResourceManager.GetString("BootSectorForm_Help_SectorCountSmall", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Number of sectors per cluster
        '''
        '''Allowed Values: {0}.
        '''</summary>
        Friend Shared ReadOnly Property BootSectorForm_Help_SectorsPerCluster() As String
            Get
                Return ResourceManager.GetString("BootSectorForm_Help_SectorsPerCluster", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Number of sectors allocated to each copy of the File Allocation Table (FAT).
        '''</summary>
        Friend Shared ReadOnly Property BootSectorForm_Help_SectorsPerFAT() As String
            Get
                Return ResourceManager.GetString("BootSectorForm_Help_SectorsPerFAT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Number of sectors per track on the disk.
        '''</summary>
        Friend Shared ReadOnly Property BootSectorForm_Help_SectorsPerTrack() As String
            Get
                Return ResourceManager.GetString("BootSectorForm_Help_SectorsPerTrack", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Typical Values:.
        '''</summary>
        Friend Shared ReadOnly Property BootSectorForm_Help_TypicalValues() As String
            Get
                Return ResourceManager.GetString("BootSectorForm_Help_TypicalValues", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unused.
        '''</summary>
        Friend Shared ReadOnly Property BootSectorForm_Help_Unused() As String
            Get
                Return ResourceManager.GetString("BootSectorForm_Help_Unused", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This field typically matches the 11-byte volume label in the root directory of the disk or has the value &quot;{0}&quot; if the volume label does not exist..
        '''</summary>
        Friend Shared ReadOnly Property BootSectorForm_Help_VolumeLabel() As String
            Get
                Return ResourceManager.GetString("BootSectorForm_Help_VolumeLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Volume Serial Number is a 32-bit random number used in conjunction with the Volume Label for removable media tracking
        '''
        '''Note: This id is typically generated by converting the current date and time into a 32-bit value.
        '''</summary>
        Friend Shared ReadOnly Property BootSectorForm_Help_VolumeSerialNumber() As String
            Get
                Return ResourceManager.GetString("BootSectorForm_Help_VolumeSerialNumber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Generate a new volume serial number based on a user supplied date and time.
        '''</summary>
        Friend Shared ReadOnly Property BootSectorForm_Help_VolumeSerialNumberButton() As String
            Get
                Return ResourceManager.GetString("BootSectorForm_Help_VolumeSerialNumberButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Convert the currently loaded image set..
        '''</summary>
        Friend Shared ReadOnly Property Flux_Convert() As String
            Get
                Return ResourceManager.GetString("Flux_Convert", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Attempt to detect the format of the disk in the selected drive by analyzing the boot sector..
        '''</summary>
        Friend Shared ReadOnly Property Flux_Detect() As String
            Get
                Return ResourceManager.GetString("Flux_Detect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Discard the currently loaded image or image set..
        '''</summary>
        Friend Shared ReadOnly Property Flux_Discard() As String
            Get
                Return ResourceManager.GetString("Flux_Discard", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Skip every other track when reading a 360 KB disk in a 1.2 MB drive..
        '''</summary>
        Friend Shared ReadOnly Property Flux_DoubleStep() As String
            Get
                Return ResourceManager.GetString("Flux_DoubleStep", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The format of the floppy disk in the selected drive..
        '''</summary>
        Friend Shared ReadOnly Property Flux_Format() As String
            Get
                Return ResourceManager.GetString("Flux_Format", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Output Image Type.
        '''</summary>
        Friend Shared ReadOnly Property Flux_ImageType() As String
            Get
                Return ResourceManager.GetString("Flux_ImageType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Import the currently loaded image..
        '''</summary>
        Friend Shared ReadOnly Property Flux_Import() As String
            Get
                Return ResourceManager.GetString("Flux_Import", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Import the currently loaded image and close this dialog..
        '''</summary>
        Friend Shared ReadOnly Property Flux_ImportClose() As String
            Get
                Return ResourceManager.GetString("Flux_ImportClose", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Read a floppy disk from the selected drive to the selected output type..
        '''</summary>
        Friend Shared ReadOnly Property Flux_Read() As String
            Get
                Return ResourceManager.GetString("Flux_Read", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save the currently loaded image set..
        '''</summary>
        Friend Shared ReadOnly Property Flux_Save() As String
            Get
                Return ResourceManager.GetString("Flux_Save", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save the currently loaded image set and close this dialog..
        '''</summary>
        Friend Shared ReadOnly Property Flux_SaveClose() As String
            Get
                Return ResourceManager.GetString("Flux_SaveClose", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save the Console Output to a log file..
        '''</summary>
        Friend Shared ReadOnly Property Flux_SaveLog() As String
            Get
                Return ResourceManager.GetString("Flux_SaveLog", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reset the Greaseweazle device to power-on default state..
        '''</summary>
        Friend Shared ReadOnly Property Greaseweazle_DeviceReset() As String
            Get
                Return ResourceManager.GetString("Greaseweazle_DeviceReset", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Available Floppy Drives.
        '''
        '''This list can be configured under 
        '''Greaseweazle Configuration in the Options menu..
        '''</summary>
        Friend Shared ReadOnly Property Greaseweazle_Drives() As String
            Get
                Return ResourceManager.GetString("Greaseweazle_Drives", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The imported file&apos;s extension..
        '''</summary>
        Friend Shared ReadOnly Property Greaseweazle_FileExt() As String
            Get
                Return ResourceManager.GetString("Greaseweazle_FileExt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The imported file’s name, or the parent folder’s name 
        '''if the Output Type is set to Flux Image Set.
        '''
        '''You can create a filename template by enclosing any
        '''number in angle brackets (&lt; &gt;). For example: Disk &lt;1&gt; of 3.
        '''
        '''The number inside the brackets will automatically
        '''increment for each subsequent read..
        '''</summary>
        Friend Shared ReadOnly Property Greaseweazle_ReadFilename() As String
            Get
                Return ResourceManager.GetString("Greaseweazle_ReadFilename", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Number of retries per seek-retry.
        '''</summary>
        Friend Shared ReadOnly Property Greaseweazle_Retries() As String
            Get
                Return ResourceManager.GetString("Greaseweazle_Retries", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Number of revolutions to read per track.
        '''</summary>
        Friend Shared ReadOnly Property Greaseweazle_Revs() As String
            Get
                Return ResourceManager.GetString("Greaseweazle_Revs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The root folder for your flux image sets.
        '''
        '''The default root folder can be configured under 
        '''Greaseweazle Configuration in the Options menu..
        '''</summary>
        Friend Shared ReadOnly Property Greaseweazle_RootFolder() As String
            Get
                Return ResourceManager.GetString("Greaseweazle_RootFolder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save a log file in the parent folder alongside the image set.
        '''
        '''The log file name can be configured under 
        '''Greaseweazle Configuration in the Options menu..
        '''</summary>
        Friend Shared ReadOnly Property Greaseweazle_SaveLog() As String
            Get
                Return ResourceManager.GetString("Greaseweazle_SaveLog", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Number of seek retries.
        '''</summary>
        Friend Shared ReadOnly Property Greaseweazle_SeekRetries() As String
            Get
                Return ResourceManager.GetString("Greaseweazle_SeekRetries", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
