'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class HelpStrings
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("DiskImageTool.HelpStrings", GetType(HelpStrings).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This Is additional data found in the Boot Sector.
        '''
        '''Note: Data highlighted in green is the bootstrap code..
        '''</summary>
        Friend Shared ReadOnly Property BootSectorForm_AdditionalData() As String
            Get
                Return ResourceManager.GetString("BootSectorForm_AdditionalData", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Allowed Values:.
        '''</summary>
        Friend Shared ReadOnly Property BootSectorForm_AllowedValues() As String
            Get
                Return ResourceManager.GetString("BootSectorForm_AllowedValues", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Allowed Values: {0}.
        '''</summary>
        Friend Shared ReadOnly Property BootSectorForm_AllowedValuesInline() As String
            Get
                Return ResourceManager.GetString("BootSectorForm_AllowedValuesInline", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Indicated to the BIOS that the sector is executable..
        '''</summary>
        Friend Shared ReadOnly Property BootSectorForm_BootSectorSignature() As String
            Get
                Return ResourceManager.GetString("BootSectorForm_BootSectorSignature", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Number of bytes in each physical sector.
        '''</summary>
        Friend Shared ReadOnly Property BootSectorForm_BytesPerSector() As String
            Get
                Return ResourceManager.GetString("BootSectorForm_BytesPerSector", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Note: This value should be {0} for all floppy disks..
        '''</summary>
        Friend Shared ReadOnly Property BootSectorForm_BytesPerSector_Note() As String
            Get
                Return ResourceManager.GetString("BootSectorForm_BytesPerSector_Note", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The disk type detected based on the current values in the Boot Record.  Changing this will set the values in the boot record to those of the selected disk type..
        '''</summary>
        Friend Shared ReadOnly Property BootSectorForm_DiskType() As String
            Get
                Return ResourceManager.GetString("BootSectorForm_DiskType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Interrupt 13h drive number.
        '''</summary>
        Friend Shared ReadOnly Property BootSectorForm_DriveNumber() As String
            Get
                Return ResourceManager.GetString("BootSectorForm_DriveNumber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 28h\tVolume Serial Number is present
        '''29h\tVolume Serial Number, Volume Label, and File System ID are present.
        '''</summary>
        Friend Shared ReadOnly Property BootSectorForm_ExtendedBootSignature() As String
            Get
                Return ResourceManager.GetString("BootSectorForm_ExtendedBootSignature", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The File System ID is informational only.
        '''</summary>
        Friend Shared ReadOnly Property BootSectorForm_FileSystemType() As String
            Get
                Return ResourceManager.GetString("BootSectorForm_FileSystemType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fixed Disk.
        '''</summary>
        Friend Shared ReadOnly Property BootSectorForm_FixedDisk() As String
            Get
                Return ResourceManager.GetString("BootSectorForm_FixedDisk", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Number of sectors preceeding the first sector of a partitioned volume
        '''
        '''Note: This value should be {0} for all floppy disks.
        '''</summary>
        Friend Shared ReadOnly Property BootSectorForm_HiddenSectors() As String
            Get
                Return ResourceManager.GetString("BootSectorForm_HiddenSectors", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This instruction indicates where the bootstrap code starts..
        '''</summary>
        Friend Shared ReadOnly Property BootSectorForm_JumpInstruction() As String
            Get
                Return ResourceManager.GetString("BootSectorForm_JumpInstruction", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Number of File Allocation Table (FAT) copies on the volume
        '''
        '''Allowed Values: Any non-zero value
        '''
        '''Note: This value should typically be set to {0}..
        '''</summary>
        Friend Shared ReadOnly Property BootSectorForm_NumberOfFATs() As String
            Get
                Return ResourceManager.GetString("BootSectorForm_NumberOfFATs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Number of physical heads (sides) on the disk.
        '''</summary>
        Friend Shared ReadOnly Property BootSectorForm_NumberOfHeads() As String
            Get
                Return ResourceManager.GetString("BootSectorForm_NumberOfHeads", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to OEM Name Identifier
        '''
        '''Can be set by a FAT implementation to any desired value
        '''
        '''Typically this is some indication of what system formatted the volume..
        '''</summary>
        Friend Shared ReadOnly Property BootSectorForm_OEMName() As String
            Get
                Return ResourceManager.GetString("BootSectorForm_OEMName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Number of reserved sectors in the reserved region of the volume starting at the first sector of the volume
        '''
        '''Allowed Values: Any non-zero value
        '''
        '''Note: This value should typically be set to {0}..
        '''</summary>
        Friend Shared ReadOnly Property BootSectorForm_ReservedSectors() As String
            Get
                Return ResourceManager.GetString("BootSectorForm_ReservedSectors", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Number of entries in the root directory
        '''
        '''Allowed Values: Value multiplied by {0} should be an even multiple of Bytes Per Sector.
        '''</summary>
        Friend Shared ReadOnly Property BootSectorForm_RootDirectoryEntries() As String
            Get
                Return ResourceManager.GetString("BootSectorForm_RootDirectoryEntries", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Total number of sectors in a FAT16 volume larger than {0} sectors
        '''
        '''Note: This value should be {1} for all floppy disks.
        '''</summary>
        Friend Shared ReadOnly Property BootSectorForm_SectorCountLarge() As String
            Get
                Return ResourceManager.GetString("BootSectorForm_SectorCountLarge", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Total number of sectors in the volume.
        '''</summary>
        Friend Shared ReadOnly Property BootSectorForm_SectorCountSmall() As String
            Get
                Return ResourceManager.GetString("BootSectorForm_SectorCountSmall", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Number of sectors per cluster.
        '''</summary>
        Friend Shared ReadOnly Property BootSectorForm_SectorsPerCluster() As String
            Get
                Return ResourceManager.GetString("BootSectorForm_SectorsPerCluster", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Number of sectors allocated to each copy of the File Allocation Table (FAT).
        '''</summary>
        Friend Shared ReadOnly Property BootSectorForm_SectorsPerFAT() As String
            Get
                Return ResourceManager.GetString("BootSectorForm_SectorsPerFAT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Number of sectors per track on the disk.
        '''</summary>
        Friend Shared ReadOnly Property BootSectorForm_SectorsPerTrack() As String
            Get
                Return ResourceManager.GetString("BootSectorForm_SectorsPerTrack", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Typical Values:.
        '''</summary>
        Friend Shared ReadOnly Property BootSectorForm_TypicalValues() As String
            Get
                Return ResourceManager.GetString("BootSectorForm_TypicalValues", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Typical Values: {0}.
        '''</summary>
        Friend Shared ReadOnly Property BootSectorForm_TypicalValuesInline() As String
            Get
                Return ResourceManager.GetString("BootSectorForm_TypicalValuesInline", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unused.
        '''</summary>
        Friend Shared ReadOnly Property BootSectorForm_Unused() As String
            Get
                Return ResourceManager.GetString("BootSectorForm_Unused", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This field typically matches the 11-byte volume label in the root directory of the disk or has the value &quot;{0}&quot; if the volume label does not exist..
        '''</summary>
        Friend Shared ReadOnly Property BootSectorForm_VolumeLabel() As String
            Get
                Return ResourceManager.GetString("BootSectorForm_VolumeLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Volume Serial Number is a 32-bit random number used in conjunction with the Volume Label for removable media tracking
        '''
        '''Note: This id is typically generated by converting the current date and time into a 32-bit value.
        '''</summary>
        Friend Shared ReadOnly Property BootSectorForm_VolumeSerialNumber() As String
            Get
                Return ResourceManager.GetString("BootSectorForm_VolumeSerialNumber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Generate a new volume serial number based on a user supplied date and time.
        '''</summary>
        Friend Shared ReadOnly Property BootSectorForm_VolumeSerialNumberButton() As String
            Get
                Return ResourceManager.GetString("BootSectorForm_VolumeSerialNumberButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Include raw flux surface data in the .86F output.
        '''
        '''Only available with PCImgCnv when the output type is .86F..
        '''</summary>
        Friend Shared ReadOnly Property Flux_86FSurfaceData() As String
            Get
                Return ResourceManager.GetString("Flux_86FSurfaceData", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Automatically save the conversion log alongside the
        '''flux image set when the conversion succeeds..
        '''</summary>
        Friend Shared ReadOnly Property Flux_AutoSaveLog() As String
            Get
                Return ResourceManager.GetString("Flux_AutoSaveLog", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Clean the heads of the floppy drive in the selected
        '''drive bay using a cleaning disk..
        '''</summary>
        Friend Shared ReadOnly Property Flux_Clean() As String
            Get
                Return ResourceManager.GetString("Flux_Clean", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Continue writing the remaining tracks if a track fails
        '''verification, instead of aborting the run..
        '''</summary>
        Friend Shared ReadOnly Property Flux_ContinueAfterFailure() As String
            Get
                Return ResourceManager.GetString("Flux_ContinueAfterFailure", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Convert the currently loaded flux image set into the
        '''selected image type without re-reading the drive..
        '''</summary>
        Friend Shared ReadOnly Property Flux_Convert() As String
            Get
                Return ResourceManager.GetString("Flux_Convert", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Attempt to detect the format of the disk in the selected drive by analyzing the boot sector..
        '''</summary>
        Friend Shared ReadOnly Property Flux_Detect() As String
            Get
                Return ResourceManager.GetString("Flux_Detect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The flux processing tool used to decode the loaded
        '''flux image set (Greaseweazle, Kryoflux, or PCImgCnv)..
        '''</summary>
        Friend Shared ReadOnly Property Flux_Device() As String
            Get
                Return ResourceManager.GetString("Flux_Device", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Discard the currently loaded image or image set..
        '''</summary>
        Friend Shared ReadOnly Property Flux_Discard() As String
            Get
                Return ResourceManager.GetString("Flux_Discard", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Skip every other track when reading a 360 KB disk in a 1.2 MB drive..
        '''</summary>
        Friend Shared ReadOnly Property Flux_DoubleStep() As String
            Get
                Return ResourceManager.GetString("Flux_DoubleStep", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Erase the floppy disk in the selected drive.
        '''
        '''When Select Tracks is enabled, only the tracks selected
        '''in the grid are erased..
        '''</summary>
        Friend Shared ReadOnly Property Flux_Erase() As String
            Get
                Return ResourceManager.GetString("Flux_Erase", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Write erase patterns to tracks that contain no data
        '''instead of leaving them as-is..
        '''</summary>
        Friend Shared ReadOnly Property Flux_EraseEmpty() As String
            Get
                Return ResourceManager.GetString("Flux_EraseEmpty", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Capture verbose Kryoflux output (read and cell-decode
        '''events) in the conversion log..
        '''</summary>
        Friend Shared ReadOnly Property Flux_ExtendedLogOutput() As String
            Get
                Return ResourceManager.GetString("Flux_ExtendedLogOutput", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The subfolder under the Root Folder where the flux
        '''image set is saved.
        '''
        '''You can create a folder name template by enclosing any
        '''number in angle brackets (&lt; &gt;). For example: Disk &lt;1&gt; of 3.
        '''
        '''The number inside the brackets will automatically
        '''increment for each subsequent read..
        '''</summary>
        Friend Shared ReadOnly Property Flux_FolderName() As String
            Get
                Return ResourceManager.GetString("Flux_FolderName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The format of the floppy disk in the selected drive..
        '''</summary>
        Friend Shared ReadOnly Property Flux_Format() As String
            Get
                Return ResourceManager.GetString("Flux_Format", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The custom destination folder for the secondary image
        '''file, used when Image Location is set to Custom..
        '''</summary>
        Friend Shared ReadOnly Property Flux_ImageFolder() As String
            Get
                Return ResourceManager.GetString("Flux_ImageFolder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Browse for the folder where the secondary image file is saved..
        '''</summary>
        Friend Shared ReadOnly Property Flux_ImageFolderBrowse() As String
            Get
                Return ResourceManager.GetString("Flux_ImageFolderBrowse", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Where the secondary image file is saved.
        '''
        '''Choose the Root Folder, the same folder as the flux
        '''image set, or a custom folder. Selecting Custom enables
        '''the Image Folder field below..
        '''</summary>
        Friend Shared ReadOnly Property Flux_ImageLocation() As String
            Get
                Return ResourceManager.GetString("Flux_ImageLocation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The primary output type for the read.
        '''
        '''Flux Image Set saves the raw flux as a .raw set that
        '''can be re-converted later. The other types (.ima, .img,
        '''.hfe, ...) decode the disk directly into a sector image.
        '''
        '''When Flux Image Set is selected, an additional decoded
        '''image can be produced during the same read by choosing
        '''an Output Type 2..
        '''</summary>
        Friend Shared ReadOnly Property Flux_ImageType() As String
            Get
                Return ResourceManager.GetString("Flux_ImageType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Import the currently loaded image into Disk Image Tool..
        '''</summary>
        Friend Shared ReadOnly Property Flux_Import() As String
            Get
                Return ResourceManager.GetString("Flux_Import", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Import the currently loaded image and close this dialog..
        '''</summary>
        Friend Shared ReadOnly Property Flux_ImportClose() As String
            Get
                Return ResourceManager.GetString("Flux_ImportClose", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to View the per-sector modifications PCImgCnv applied during conversion..
        '''</summary>
        Friend Shared ReadOnly Property Flux_Modifications() As String
            Get
                Return ResourceManager.GetString("Flux_Modifications", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Skip post-write verification.
        '''
        '''Faster but does not detect write errors..
        '''</summary>
        Friend Shared ReadOnly Property Flux_NoVerify() As String
            Get
                Return ResourceManager.GetString("Flux_NoVerify", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Open a different flux image set or sector image to convert..
        '''</summary>
        Friend Shared ReadOnly Property Flux_OpenFile() As String
            Get
                Return ResourceManager.GetString("Flux_OpenFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to When the same flux set has been processed by more than
        '''one tool, pick which tool&apos;s output is used for import..
        '''</summary>
        Friend Shared ReadOnly Property Flux_OutputSource() As String
            Get
                Return ResourceManager.GetString("Flux_OutputSource", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An optional second output produced alongside the flux
        '''image set during the same read.
        '''
        '''Available only when the primary output type is Flux
        '''Image Set. The selected type is decoded from the disk
        '''and saved to the location chosen below..
        '''</summary>
        Friend Shared ReadOnly Property Flux_OutputType2() As String
            Get
                Return ResourceManager.GetString("Flux_OutputType2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Erase each track before writing it.
        '''
        '''Slower but more reliable on worn or previously formatted media..
        '''</summary>
        Friend Shared ReadOnly Property Flux_PreErase() As String
            Get
                Return ResourceManager.GetString("Flux_PreErase", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Filename prefix for the .raw track files in the flux
        '''image set (for example, &quot;track&quot; produces track00.0.raw,
        '''track00.1.raw, ...).
        '''
        '''You can create a prefix template by enclosing any
        '''number in angle brackets (&lt; &gt;). For example: side&lt;1&gt;.
        '''
        '''The number inside the brackets will automatically
        '''increment for each subsequent read..
        '''</summary>
        Friend Shared ReadOnly Property Flux_PrefixName() As String
            Get
                Return ResourceManager.GetString("Flux_PrefixName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Preview the contents of the disk in the selected drive
        '''without saving an image, or preview the currently
        '''loaded image.
        '''
        '''For an unread disk, the first track is read and the
        '''directory listing is displayed..
        '''</summary>
        Friend Shared ReadOnly Property Flux_Preview() As String
            Get
                Return ResourceManager.GetString("Flux_Preview", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Preview the contents of the currently converted image..
        '''</summary>
        Friend Shared ReadOnly Property Flux_PreviewConvert() As String
            Get
                Return ResourceManager.GetString("Flux_PreviewConvert", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Run the conversion against the currently loaded flux
        '''image set.
        '''
        '''When Select Tracks is enabled, only the tracks selected
        '''in the grid are reconverted..
        '''</summary>
        Friend Shared ReadOnly Property Flux_Process() As String
            Get
                Return ResourceManager.GetString("Flux_Process", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Read a floppy disk from the selected drive to the selected output type.
        '''
        '''When Select Tracks is enabled, only the tracks
        '''selected in the grid below are re-read..
        '''</summary>
        Friend Shared ReadOnly Property Flux_Read() As String
            Get
                Return ResourceManager.GetString("Flux_Read", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Open an existing flux image set (.raw) and load its
        '''current state into the track grid.
        '''
        '''The form is then placed in select-tracks mode so
        '''individual tracks can be re-read against the original
        '''flux set..
        '''</summary>
        Friend Shared ReadOnly Property Flux_Refine() As String
            Get
                Return ResourceManager.GetString("Flux_Refine", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Apply the saved track layout while reconverting with PCImgCnv.
        '''
        '''Only available when a track layout has been generated..
        '''</summary>
        Friend Shared ReadOnly Property Flux_Remaster() As String
            Get
                Return ResourceManager.GetString("Flux_Remaster", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Browse for the root folder where flux image sets are saved..
        '''</summary>
        Friend Shared ReadOnly Property Flux_RootBrowse() As String
            Get
                Return ResourceManager.GetString("Flux_RootBrowse", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save the currently loaded flux image set to the chosen destination..
        '''</summary>
        Friend Shared ReadOnly Property Flux_Save() As String
            Get
                Return ResourceManager.GetString("Flux_Save", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save the currently loaded flux image set and close this dialog..
        '''</summary>
        Friend Shared ReadOnly Property Flux_SaveClose() As String
            Get
                Return ResourceManager.GetString("Flux_SaveClose", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save the Console Output to a log file..
        '''</summary>
        Friend Shared ReadOnly Property Flux_SaveLog() As String
            Get
                Return ResourceManager.GetString("Flux_SaveLog", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enable per-track selection in the grid below.
        '''
        '''When checked, only the tracks selected in the grid
        '''are re-read on the next Read..
        '''</summary>
        Friend Shared ReadOnly Property Flux_SelectTracks() As String
            Get
                Return ResourceManager.GetString("Flux_SelectTracks", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Wrap or unwrap the current number with angle brackets
        '''(&lt; &gt;) in the focused filename, folder, or prefix field.
        '''
        '''A bracketed number is auto-incremented after each read..
        '''</summary>
        Friend Shared ReadOnly Property Flux_ToggleSequence() As String
            Get
                Return ResourceManager.GetString("Flux_ToggleSequence", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to View the per-track layout PCImgCnv produced during conversion..
        '''</summary>
        Friend Shared ReadOnly Property Flux_TrackLayout() As String
            Get
                Return ResourceManager.GetString("Flux_TrackLayout", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Verify the currently loaded flux image set using
        '''Kryoflux without re-reading the drive.
        '''
        '''Verification results for each track are displayed
        '''in the grid above..
        '''</summary>
        Friend Shared ReadOnly Property Flux_Verify() As String
            Get
                Return ResourceManager.GetString("Flux_Verify", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Write the loaded image to the floppy disk in the
        '''selected drive.
        '''
        '''When Select Tracks is enabled, only the tracks selected
        '''in the grid are written..
        '''</summary>
        Friend Shared ReadOnly Property Flux_Write() As String
            Get
                Return ResourceManager.GetString("Flux_Write", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Number of cylinders to clean.
        '''
        '''Most drives use 40 (5.25&quot; double density) or 80
        '''(everything else)..
        '''</summary>
        Friend Shared ReadOnly Property Greaseweazle_CleanCyls() As String
            Get
                Return ResourceManager.GetString("Greaseweazle_CleanCyls", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Time in milliseconds the head will linger on each
        '''cylinder during a pass..
        '''</summary>
        Friend Shared ReadOnly Property Greaseweazle_CleanLinger() As String
            Get
                Return ResourceManager.GetString("Greaseweazle_CleanLinger", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Number of cleaning passes to make..
        '''</summary>
        Friend Shared ReadOnly Property Greaseweazle_CleanPasses() As String
            Get
                Return ResourceManager.GetString("Greaseweazle_CleanPasses", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reset the Greaseweazle device to power-on default state..
        '''</summary>
        Friend Shared ReadOnly Property Greaseweazle_DeviceReset() As String
            Get
                Return ResourceManager.GetString("Greaseweazle_DeviceReset", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Available Floppy Drives.
        '''
        '''This list can be configured under 
        '''Greaseweazle Configuration in the Options menu..
        '''</summary>
        Friend Shared ReadOnly Property Greaseweazle_Drives() As String
            Get
                Return ResourceManager.GetString("Greaseweazle_Drives", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The output file&apos;s extension..
        '''</summary>
        Friend Shared ReadOnly Property Greaseweazle_FileExt() As String
            Get
                Return ResourceManager.GetString("Greaseweazle_FileExt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The file extension for the secondary output..
        '''</summary>
        Friend Shared ReadOnly Property Greaseweazle_FileExt2() As String
            Get
                Return ResourceManager.GetString("Greaseweazle_FileExt2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Erase using a high-frequency signal instead of the
        '''default DC erase. Use this for media that does not
        '''respond to a normal erase..
        '''</summary>
        Friend Shared ReadOnly Property Greaseweazle_Hfreq() As String
            Get
                Return ResourceManager.GetString("Greaseweazle_Hfreq", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The output file’s name.
        '''
        '''You can create a filename template by enclosing any
        '''number in angle brackets (&lt; &gt;). For example: Disk &lt;1&gt; of 3.
        '''
        '''The number inside the brackets will automatically
        '''increment for each subsequent read..
        '''</summary>
        Friend Shared ReadOnly Property Greaseweazle_ReadFilename() As String
            Get
                Return ResourceManager.GetString("Greaseweazle_ReadFilename", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Maximum number of read retries per track when a read error is encountered..
        '''</summary>
        Friend Shared ReadOnly Property Greaseweazle_Retries() As String
            Get
                Return ResourceManager.GetString("Greaseweazle_Retries", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Number of revolutions to read per track.
        '''</summary>
        Friend Shared ReadOnly Property Greaseweazle_Revs() As String
            Get
                Return ResourceManager.GetString("Greaseweazle_Revs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The root folder for your flux image sets.
        '''
        '''The default root folder can be configured under 
        '''Greaseweazle Configuration in the Options menu..
        '''</summary>
        Friend Shared ReadOnly Property Greaseweazle_RootFolder() As String
            Get
                Return ResourceManager.GetString("Greaseweazle_RootFolder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save a log file alongside the flux image set,
        '''capturing the Greaseweazle console output for the run.
        '''
        '''The log file name can be configured under
        '''Greaseweazle Configuration in the Options menu..
        '''</summary>
        Friend Shared ReadOnly Property Greaseweazle_SaveLog() As String
            Get
                Return ResourceManager.GetString("Greaseweazle_SaveLog", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Maximum number of times the drive head re-seeks to a track if all read retries fail..
        '''</summary>
        Friend Shared ReadOnly Property Greaseweazle_SeekRetries() As String
            Get
                Return ResourceManager.GetString("Greaseweazle_SeekRetries", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
