Module OEMIDLookup
    Public Function GetOEMIDDictionary() As Dictionary(Of UInteger, List(Of OEMID))
        Dim OEMIDList As New List(Of OEMID) From {
            New OEMID(&HA4FBF36D&, "-SHADOW-"),
            New OEMID(&HC6CE8A87&, "..DOS4.0"),
            New OEMID(&H62084C99&, "688AS EA", "English", "Electronic Arts", "688 Attack Sub Master Disk"),
            New OEMID(&H263742BA&, "688AS EA", "English", "Electronic Arts", "688 Attack Sub Master Disk 1"),
            New OEMID(&H31482872&, "688AS EA", "English", "Electronic Arts", "688 Attack Sub Master Disk 2"),
            New OEMID(&H231A83E&, "ALF  2.0"),
            New OEMID(&HB4140C43&, "ALF  3.0"),
            New OEMID(&H7096EE00&, "ALF  3.0"),
            New OEMID(&HE981E850&, "ALF  3.0"),
            New OEMID(&H20AE7ABE&, "C ZDS3.3"),
            New OEMID(&H8DA9C947&, "BOOT 1.2", "German"),
            New OEMID(&H5AB69A70&, "BOOT 1.2", "German"),
            New OEMID(&H72EE604C&, "CACHET  "),
            New OEMID(&H3C50923A&, "Caldwell", "English", "New World Computing", "Might and Magic ]I[ Disk 1  1.2mb Version"),
            New OEMID(&H11A55D39&, "Caldwell", "English", "New World Computing", "Might and Magic ]I[ Disk 2  1.2mb Version"),
            New OEMID(&HAF61838&, "Caldwell", "English", "New World Computing", "Might and Magic ]I[ Disk 3  1.2mb Version"),
            New OEMID(&HF4E0FC38&, "Caldwell", "English", "New World Computing", "Might and Magic ]I[ Disk 1 720k Version"),
            New OEMID(&HD915333B&, "Caldwell", "English", "New World Computing", "Might and Magic ]I[ Disk 2 720k Version"),
            New OEMID(&HC246763A&, "Caldwell", "English", "New World Computing", "Might and Magic ]I[ Disk 3 720k Version"),
            New OEMID(&H82FEAD3D&, "Caldwell", "English", "New World Computing", "Might and Magic ]I[ Disk 4 720k Version"),
            New OEMID(&H99ADE83C&, "Caldwell", "English", "New World Computing", "Might and Magic ]I[ Disk 5 720k Version"),
            New OEMID(&H331BAC89&, "Caldwell", "English", "New World Computing", "Might and Magic ]I[ Disk 1  360k Version"),
            New OEMID(&H1EEE638A&, "Caldwell", "English", "New World Computing", "Might and Magic ]I[ Disk 2  360k Version"),
            New OEMID(&H5BD268B&, "Caldwell", "English", "New World Computing", "Might and Magic ]I[ Disk 3  360k Version"),
            New OEMID(&H4505FD8C&, "Caldwell", "English", "New World Computing", "Might and Magic ]I[ Disk 4  360k Version"),
            New OEMID(&H5E56B88D&, "Caldwell", "English", "New World Computing", "Might and Magic ]I[ Disk 5  360k Version"),
            New OEMID(&H73A3778E&, "Caldwell", "English", "New World Computing", "Might and Magic ]I[ Disk 6  360k Version"),
            New OEMID(&H68F0328F&, "Caldwell", "English", "New World Computing", "Might and Magic ]I[ Disk 7  360k Version"),
            New OEMID(&HF2D2C180&, "Caldwell", "English", "New World Computing", "Might and Magic ]I[ Disk 8  360k Version"),
            New OEMID(&HE9818481&, "Caldwell", "English", "New World Computing", "Might and Magic ]I[ Disk 9  360k Version"),
            New OEMID(&H1D4B1A1E&, "Caldwell", "English", "New World Computing", "Might and Magic ]I[ Disk 10 360k Version"),
            New OEMID(&H5F1BE4D1&, "CCC  2.1", "English", "Compaq"),
            New OEMID(&HD7FB8823&, "CH-FOR15"),
            New OEMID(&HC91B0027&, "CH-FOR16"),
            New OEMID(&H69C11AA5&, "CH-FOR18"),
            New OEMID(&HCE2D6ECF&, "CMAST2.0"),
            New OEMID(&H3151C66B&, "DIGITAL "),
            New OEMID(&H9796E9A5&, "DIGITAL "),
            New OEMID(&HF54A6EF8&, "DIGITAL "),
            New OEMID(&H82D411E6&, "DOS 4.01"),
            New OEMID(&H76A97243&, "EPS 2.11"),
            New OEMID(&H6E55822D&, "FORMATQM"),
            New OEMID(&HAAA07D93&, "GAZELLE "),
            New OEMID(&HB9475667&, "HILOW1.☺", "English", "Iron Byte", "NARCOPOLICE"),
            New OEMID(&H54B3847A&, "HILOW1.☺", "English", "Iron Byte", "NARCOPOLICE"),
            New OEMID(&H4C04C757&, "HILOW1.☻", "English", "Iron Byte", "NARCOPOLICE DISK 2 OF 2"),
            New OEMID(&H640C56D5&, "HILOW1.0", "English", "Iron Byte", "BUGGYRANGER"),
            New OEMID(&HB3C42CAD&, "I93 1.00"),
            New OEMID(&H5EB98F7B&, "IBM  2.0"),
            New OEMID(&HD088AAE9&, "IBM  2.0", "French"),
            New OEMID(&H58BB4185&, "IBM  3.0"),
            New OEMID(&HFD68F648&, "IBM  3.0", "English", "Compaq"),
            New OEMID(&H440CF965&, "IBM  3.1"),
            New OEMID(&H148EBE9E&, "IBM  3.1"),
            New OEMID(&H3CD5390D&, "IBM  3.1", "English", "Compaq"),
            New OEMID(&H7AD69436&, "IBM  3.2"),
            New OEMID(&H66660092&, "IBM  3.2"),
            New OEMID(&HA6003920&, "IBM  3.2", "English", "Compaq"),
            New OEMID(&H38B1373&, "IBM  3.2", "English", "Sofsource"),
            New OEMID(&H3519D43D&, "IBM  3.2", "English", "Falk Data Systems"),
            New OEMID(&H96B7BEAA&, "IBM  3.2", "German"),
            New OEMID(&H18BA4260&, "IBM  3.3", "English", "Compaq"),
            New OEMID(&HA813EDA9&, "IBM  3.3"),
            New OEMID(&HFC1650BE&, "IBM  3.3"),
            New OEMID(&HE7E28CB3&, "IBM  3.3"),
            New OEMID(&HBBB8D363&, "IBM  3.3", "English", "Accolade", "Star Control 1"),
            New OEMID(&HD5A08E3B&, "IBM  3.3"),
            New OEMID(&H351A15CD&, "IBM  3.3", "English", "Falk Data Systems"),
            New OEMID(&HA0DFCF7A&, "IBM  3.3", "English", "Falk Data Systems"),
            New OEMID(&H50EC1B86&, "IBM  3.3", "French"),
            New OEMID(&HC63EA411&, "IBM  3.3", "French"),
            New OEMID(&H55957DBE&, "IBM  3.3", "German"),
            New OEMID(&H90E549B9&, "IBM  3.3", "German"),
            New OEMID(&HFD8B56C&, "IBM  3.3", "German"),
            New OEMID(&H44F2B954&, "IBM  3.3", "Spanish"),
            New OEMID(&H47C377A8&, "IBM  3.3", "Swedish"),
            New OEMID(&HCA5FCC71&, "IBM  4.0"),
            New OEMID(&HD6D774CA&, "IBM  4.0", "French"),
            New OEMID(&H787A6427&, "IBM  4.0", "Spanish"),
            New OEMID(&H47E20088&, "IBM 4.01"),
            New OEMID(&H47E20088&, "IBM  4.1"),
            New OEMID(&H3F6176DF&, "IBM  5.0"),
            New OEMID(&HA157CE&, "IBM  5.0"),
            New OEMID(&H42705487&, "IBM  5.0", "French"),
            New OEMID(&H1E9133C3&, "IBM  5.0", "German"),
            New OEMID(&HFA3E60A8&, "IBM 10.1"),
            New OEMID(&HC5584353&, "IBM 10.2"),
            New OEMID(&H19410C4&, "IBM 20.0"),
            New OEMID(&HDC004D1A&, "IBM 20.0"),
            New OEMID(&H2E89BBB4&, "IBM PNCI"),
            New OEMID(&H4495837A&, "IBM PNCI"),
            New OEMID(&H4E1A74D4&, "IBM PNCI"),
            New OEMID(&HFA938DDA&, "IBM PNCI"),
            New OEMID(&H5C05F009&, "IBM PNCI"),
            New OEMID(&H7AD69436&, "IBMMS3.2"),
            New OEMID(&H63DCC6E5&, "IBMMS3.2"),
            New OEMID(&HD5A08E3B&, "IBMMS3.3"),
            New OEMID(&HCA5FCC71&, "IBMMS4.0"),
            New OEMID(&HA082BC0&, "INDY 500", "English", "Electronic Arts", "Indianapolis 500 Disk 1"),
            New OEMID(&HB517A9A9&, "INDY 500", "English", "Electronic Arts", "Indianapolis 500 Disk 2"),
            New OEMID(&HF771E16A&, "INDY 500", "English", "Electronic Arts", "Indianapolis 500 Disk"),
            New OEMID(&HB3C42CAD&, "INSIGNIA"),
            New OEMID(&HD5A08E3B&, "KEY DISK"),
            New OEMID(&HC53FAC5A&, "KEY DISK", "English", "AEG Olympia"),
            New OEMID(&HC902D242&, "LHX 3.5 ", "English", "Electronic Arts", "LHX: ATTACK CHOPPER Disk"),
            New OEMID(&H15860A5A&, "LHX ONE ", "English", "Electronic Arts", "LHX: ATTACK CHOPPER Disk One"),
            New OEMID(&HF47AF861&, "LHX TWO ", "English", "Electronic Arts", "LHX: ATTACK CHOPPER Disk Two"),
            New OEMID(&H8CD8F888&, "MagicISO"),
            New OEMID(&H9B0E679E&, "MSC 3.1 "),
            New OEMID(&HEB85220D&, "MSDMF3.2"),
            New OEMID(&H2D34342E&, "MSDOS3.2"),
            New OEMID(&H63DCC6E5&, "MSDOS3.2"),
            New OEMID(&H58FAE0BA&, "MSDOS3.2"),
            New OEMID(&HD7CDA53E&, "MSDOS3.2"),
            New OEMID(&H7186F853&, "MSDOS3.2", "French"),
            New OEMID(&H461FE7DE&, "MSDOS3.2", "French"),
            New OEMID(&H6EA1666A&, "MSDOS3.2", "German"),
            New OEMID(&H37F00296&, "MSDOS3.2", "German"),
            New OEMID(&HB3C42CAD&, "MSDOS3.3"),
            New OEMID(&H17120C24&, "MSDOS3.3"),
            New OEMID(&H5045D72B&, "MSDOS3.3"),
            New OEMID(&HD5A08E3B&, "MSDOS3.3"),
            New OEMID(&HF8BD5277&, "MSDOS3.3", "French"),
            New OEMID(&H6215D36A&, "MSDOS3.3", "French"),
            New OEMID(&H6215D36A&, "MSDOS3.3", "French"),
            New OEMID(&HBA7919EB&, "MSDOS3.3", "German"),
            New OEMID(&H38EAB531&, "MSDOS3.3", "Spanish"),
            New OEMID(&HDB11BCE5&, "MSDOS4.0"),
            New OEMID(&H70386805&, "MSDOS4.0", "Spanish"),
            New OEMID(&H4767DBA2&, "MSDOS4.0", "French"),
            New OEMID(&HBEEAD529&, "MSDOS4.0", "German"),
            New OEMID(&HFE944220&, "MSDOS5.0"),
            New OEMID(&HFE944220&, "MSDBL6.0"),
            New OEMID(&HFE944220&, "MSDSP6.0"),
            New OEMID(&H93282B6B&, "MSDOS5.0"),
            New OEMID(&HD3C0FBEF&, "MSDOS5.0", "French"),
            New OEMID(&H7E3C7397&, "MSDOS5.0", "French"),
            New OEMID(&H5D696A06&, "MSDOS5.0", "German"),
            New OEMID(&HF043E2A8&, "MSDOS5.0", "German"),
            New OEMID(&HDC98D56D&, "MSDOS5.0", "Italian"),
            New OEMID(&HF8066DEC&, "MSDOS5.0", "Italian"),
            New OEMID(&HEEB2E10D&, "MSDOS5.0", "Spanish"),
            New OEMID(&H6A18BCFC&, "MSDOS5.0", "Spanish"),
            New OEMID(&HFA32C52E&, "MSDOS5.0", "Swedish"),
            New OEMID(&H1D1B49D&, "MSDOS6.0"),
            New OEMID(&HA975B7F6&, "MSWIN4.0"),
            New OEMID(&H9EF2AF2E&, "MSWIN4.1"),
            New OEMID(&H1D765B56&, "NEC 2.00"),
            New OEMID(&H342A7190&, "NECIS3.3"),
            New OEMID(&H3E12D96&, "NWDOS7.0", "German"),
            New OEMID(&H5B0DA127&, " Norton "),
            New OEMID(&H74259F76&, "Olivetti"),
            New OEMID(&HABF90357&, "PC Tools"),
            New OEMID(&H373BC7C4&, "PC Tools"),
            New OEMID(&H4CEA4F0B&, "PC Tools"),
            New OEMID(&H61AEADE2&, "PC Tools", "French"),
            New OEMID(&H23318A0D&, "PCFormat"),
            New OEMID(&HDE92B409&, "PCFormat"),
            New OEMID(&H10739392&, "PCFormat"),
            New OEMID(&HCE432EBD&, "PCFormat"),
            New OEMID(&H9F531693&, "PCFormat", "French"),
            New OEMID(&HA96BA8C5&, "PCFormat", "French"),
            New OEMID(&HEDE849B9&, "PCFormat", "German"),
            New OEMID(&H8BE98DEC&, "ProCopy "),
            New OEMID(&H6D055CC4&, "PSA  3.1"),
            New OEMID(&H9079EC60&, "PSA  3.1"),
            New OEMID(&HD2318C04&, "PSA  3.2"),
            New OEMID(&HFBF4FA19&, "PSA  3.2"),
            New OEMID(&H341237B8&, "QuickDOS"),
            New OEMID(&HD6F1C2CF&, "Retal1.0", "English", "Ocean Software", "RETALIATOR"),
            New OEMID(&H63DCC6E5&, "SANYO3.2"),
            New OEMID(&H5A0CF3DE&, "StupnDOS"),
            New OEMID(&H10E95043&, "StupnDOS"),
            New OEMID(&HE32BB64C&, "S.BERMAN"),
            New OEMID(&H4B0F3969&, "SU25 3-1", "English", "Electronic Arts", "STORMOVIK: THE SU-25 SOVIET ATTACK FIGHTER DISK ONE"),
            New OEMID(&H8F51BE81&, "SU25 3-2", "English", "Electronic Arts", "STORMOVIK: THE SU-25 SOVIET ATTACK FIGHTER DISK TWO"),
            New OEMID(&H4B0F3969&, "SU25 5-1", "English", "Electronic Arts", "STORMOVIK: THE SU-25 SOVIET ATTACK FIGHTER DISK ONE"),
            New OEMID(&H8F51BE81&, "SU25 5-2", "English", "Electronic Arts", "STORMOVIK: THE SU-25 SOVIET ATTACK FIGHTER DISK TWO"),
            New OEMID(&H9C039DAC&, "SU25 5-3", "English", "Electronic Arts", "STORMOVIK: THE SU-25 SOVIET ATTACK FIGHTER DISK THREE"),
            New OEMID(&H7BC949F3&, "T V2.11 ", "English", "Toshiba"),
            New OEMID(&HC1C6ECB8&, "T V4.00 ", "French"),
            New OEMID(&H577983D2&, "TAN  3.2", "English", "Tandy"),
            New OEMID(&H2EC74C3B&, "TAN  3.2", "French", "Tandy"),
            New OEMID(&H847631E8&, "TAN  3.3", "English", "Tandy"),
            New OEMID(&HC82880D8&, "TAN  3.3", "French", "Tandy"),
            New OEMID(&H69B1B489&, "Tandy557", "English", "Tandy"),
            New OEMID(&HA26247F1&, "TracerST"),
            New OEMID(&H2ED639B9&, "TLC DSK ", "English", "The Learning Company", "Math Rabbit Program Disk"),
            New OEMID(&H6A55F646&, "TLC DSK ", "English", "The Learning Company", "Math Rabbit Program Disk"),
            New OEMID(&HCBEE554B&, "TLC DSK ", "English", "The Learning Company", "Challenge of the Ancient Empires! Program/Artifacts Disk"),
            New OEMID(&H638C6598&, "TLC DSK ", "English", "The Learning Company", "OutNumbered! Program Disk"),
            New OEMID(&H4232FB12&, "TLC DSK ", "English", "The Learning Company", "Treasure Mountain! Program Disk"),
            New OEMID(&HBFF3E647&, "TLC DSK ", "English", "The Learning Company", "Treasure Mountain! Disk 1"),
            New OEMID(&HB39D0FE7&, "TLC DSK ", "English", "The Learning Company", "Treasure Mountain! Disk 2"),
            New OEMID(&HABF90357&, "UBI-SOFT", "English", "UBI Soft"),
            New OEMID(&H9030CB3B&, "VGACPY45", "German"),
            New OEMID(&HECD328C3&, "VGACPY46", "German"),
            New OEMID(&HCA33CAD&, "VGACPY51"),
            New OEMID(&H9688B3F1&, "VGACP600", "German"),
            New OEMID(&H1F29F8C6&, "VGACP625"),
            New OEMID(&H87344D76&, "VGACP625", "German"),
            New OEMID(&HB9067457&, "WINIMAGE"),
            New OEMID(&H78E72263&, "WINIMAGE"),
            New OEMID(&H9C179396&, "X-DBS1.0"),
            New OEMID(&HCB438B3C&, "XTF-BOOT", "English", "Executive Systems"),
            New OEMID(&H7E03A60A&, "XTREEWIN", "English", "Executive Systems"),
            New OEMID(&HD634AA9A&, "YAC 1   ", "English", "Electronic Arts", "Yeager Air Combat Disk 1"),
            New OEMID(&H45C0F42C&, "YAC 2   ", "English", "Electronic Arts", "Yeager Air Combat Disk 2"),
            New OEMID(&HE842C73&, "YAC 3   ", "English", "Electronic Arts", "Yeager Air Combat Disk 3"),
            New OEMID(&H252B23AF&, "YAC 4   ", "English", "Electronic Arts", "Yeager Air Combat Disk 4"),
            New OEMID(&HEA4834E7&, "YAC 1&2 ", "English", "Electronic Arts", "Yeager Air Combat Disks 1 & 2"),
            New OEMID(&H90271314&, "YAC 3&4 ", "English", "Electronic Arts", "Yeager Air Combat Disks 3 & 4")
        }

        Dim Result = New Dictionary(Of UInteger, List(Of OEMID))
        For Each OEMID In OEMIDList
            Dim L As List(Of OEMID)
            If Result.ContainsKey(OEMID.CRC32) Then
                L = Result.Item(OEMID.CRC32)
            Else
                L = New List(Of OEMID)
                Result.Add(OEMID.CRC32, L)
            End If
            L.add(OEMID)
        Next

        Return Result
    End Function
End Module
Public Class OEMID
    Public Property CRC32 As UInteger
    Public Property ID As String
    Public Property Language As String = "English"
    Public Property Company As String = ""
    Public Property Description As String = ""

    Public Sub New(CRC32 As UInteger, ID As String, Optional Language As String = "English", Optional Company As String = "", Optional Description As String = "")
        _CRC32 = CRC32
        _ID = ID
        _Language = Language
        _Company = Company
        _Description = Description
    End Sub
End Class
