Module OEMIDLookup
    Public Function GetOEMIDDictionary() As Dictionary(Of UInteger, OEMIDList)
        Dim Result As New Dictionary(Of UInteger, OEMIDList) From {
            {&HC6CE8A87&, GetOEMIDList("..DOS4.0", "English")},
            {&H62084C99&, GetOEMIDList("688AS EA", "English")},
            {&H231A83E&, GetOEMIDList("ALF  2.0", "English")},
            {&HB4140C43&, GetOEMIDList("ALF  3.0", "English")},
            {&H7096EE00&, GetOEMIDList("ALF  3.0", "English")},
            {&HE981E850&, GetOEMIDList("ALF  3.0", "English")},
            {&H20AE7ABE&, GetOEMIDList("C ZDS3.3", "English")},
            {&HD7FB8823&, GetOEMIDList("CH-FOR15", "English")},
            {&HC91B0027&, GetOEMIDList("CH-FOR16", "English")},
            {&H69C11AA5&, GetOEMIDList("CH-FOR18", "English")},
            {&HCE2D6ECF&, GetOEMIDList("CMAST2.0", "English")},
            {&H6E55822D&, GetOEMIDList("FORMATQM", "English")},
            {&H5EB98F7B&, GetOEMIDList("IBM  2.0", "English")},
            {&H58BB4185&, GetOEMIDList("IBM  3.0", "English")},
            {&H440CF965&, GetOEMIDList("IBM  3.1", "English")},
            {&H148EBE9E&, GetOEMIDList("IBM  3.1", "English")},
            {&H3CD5390D&, GetOEMIDList("IBM  3.1", "English")},
            {&H7AD69436&, GetOEMIDList("IBM  3.2,IBMMS3.2", "English")},
            {&H66660092&, GetOEMIDList("IBM  3.2", "English")},
            {&HA6003920&, GetOEMIDList("IBM  3.2", "English")},
            {&H96B7BEAA&, GetOEMIDList("IBM  3.2", "German")},
            {&H18BA4260&, GetOEMIDList("IBM  3.3", "English")},
            {&HA813EDA9&, GetOEMIDList("IBM  3.3", "English")},
            {&HFC1650BE&, GetOEMIDList("IBM  3.3", "English")},
            {&HE7E28CB3&, GetOEMIDList("IBM  3.3", "English")},
            {&HBBB8D363&, GetOEMIDList("IBM  3.3", "English")},
            {&HD5A08E3B&, GetOEMIDList("IBM  3.3,KEY DISK,MSDOS3.3", "English")},
            {&H50EC1B86&, GetOEMIDList("IBM  3.3", "French")},
            {&HC63EA411&, GetOEMIDList("IBM  3.3", "French")},
            {&H55957DBE&, GetOEMIDList("IBM  3.3", "German")},
            {&H90E549B9&, GetOEMIDList("IBM  3.3", "German")},
            {&HFD8B56C&, GetOEMIDList("IBM  3.3", "German")},
            {&HCA5FCC71&, GetOEMIDList("IBM  4.0,IBMMS4.0", "English")},
            {&H47E20088&, GetOEMIDList("IBM  4.1,IBM 4.01", "English")},
            {&H3F6176DF&, GetOEMIDList("IBM  5.0", "English")},
            {&HA157CE&, GetOEMIDList("IBM  5.0", "English")},
            {&H42705487&, GetOEMIDList("IBM  5.0", "French")},
            {&H1E9133C3&, GetOEMIDList("IBM  5.0", "German")},
            {&HC5584353&, GetOEMIDList("IBM 10.2", "English")},
            {&H19410C4&, GetOEMIDList("IBM 20.0", "English")},
            {&HDC004D1A&, GetOEMIDList("IBM 20.0", "English")},
            {&H4495837A&, GetOEMIDList("IBM PNCI", "English")},
            {&H4E1A74D4&, GetOEMIDList("IBM PNCI", "English")},
            {&HFA938DDA&, GetOEMIDList("IBM PNCI", "English")},
            {&HC53FAC5A&, GetOEMIDList("KEY DISK", "English")},
            {&HF47AF861&, GetOEMIDList("LHX TWO ", "English")},
            {&H8CD8F888&, GetOEMIDList("MagicISO", "English")},
            {&H9B0E679E&, GetOEMIDList("MSC 3.1 ", "English")},
            {&HEB85220D&, GetOEMIDList("MSDMF3.2", "English")},
            {&H2D34342E&, GetOEMIDList("MSDOS3.2", "English")},
            {&H63DCC6E5&, GetOEMIDList("MSDOS3.2", "English")},
            {&H58FAE0BA&, GetOEMIDList("MSDOS3.2", "English")},
            {&HD7CDA53E&, GetOEMIDList("MSDOS3.2", "English")},
            {&H7186F853&, GetOEMIDList("MSDOS3.2", "French")},
            {&H461FE7DE&, GetOEMIDList("MSDOS3.2", "French")},
            {&H6EA1666A&, GetOEMIDList("MSDOS3.2", "German")},
            {&HB3C42CAD&, GetOEMIDList("MSDOS3.3,INSIGNIA,I93 1.00", "English")},
            {&H17120C24&, GetOEMIDList("MSDOS3.3", "English")},
            {&H5045D72B&, GetOEMIDList("MSDOS3.3", "English")},
            {&HF8BD5277&, GetOEMIDList("MSDOS3.3", "French")},
            {&HBA7919EB&, GetOEMIDList("MSDOS3.3", "German")},
            {&HDB11BCE5&, GetOEMIDList("MSDOS4.0", "English")},
            {&H70386805&, GetOEMIDList("MSDOS4.0", "English")},
            {&H4767DBA2&, GetOEMIDList("MSDOS4.0", "French")},
            {&HFE944220&, GetOEMIDList("MSDOS5.0,MSDBL6.0,MSDSP6.0", "English")},
            {&H93282B6B&, GetOEMIDList("MSDOS5.0", "English")},
            {&HD3C0FBEF&, GetOEMIDList("MSDOS5.0", "French")},
            {&H7E3C7397&, GetOEMIDList("MSDOS5.0", "French")},
            {&H5D696A06&, GetOEMIDList("MSDOS5.0", "German")},
            {&HDC98D56D&, GetOEMIDList("MSDOS5.0", "Italian")},
            {&HEEB2E10D&, GetOEMIDList("MSDOS5.0", "Spanish")},
            {&H6A18BCFC&, GetOEMIDList("MSDOS5.0", "Spanish")},
            {&H1D1B49D&, GetOEMIDList("MSDOS6.0", "English")},
            {&HA975B7F6&, GetOEMIDList("MSWIN4.0", "English")},
            {&H342A7190&, GetOEMIDList("NECIS3.3", "English")},
            {&H3E12D96&, GetOEMIDList("NWDOS7.0", "German")},
            {&H74259F76&, GetOEMIDList("Olivetti", "English")},
            {&HABF90357&, GetOEMIDList("PC Tools,UBI-SOFT", "English")},
            {&H373BC7C4&, GetOEMIDList("PC Tools", "English")},
            {&H4CEA4F0B&, GetOEMIDList("PC Tools", "English")},
            {&H61AEADE2&, GetOEMIDList("PC Tools", "French")},
            {&H23318A0D&, GetOEMIDList("PCFormat", "English")},
            {&HDE92B409&, GetOEMIDList("PCFormat", "English")},
            {&H10739392&, GetOEMIDList("PCFormat", "English")},
            {&H8BE98DEC&, GetOEMIDList("ProCopy ", "English")},
            {&H6D055CC4&, GetOEMIDList("PSA  3.1", "English")},
            {&HD2318C04&, GetOEMIDList("PSA  3.2", "English")},
            {&HFBF4FA19&, GetOEMIDList("PSA  3.2", "English")},
            {&HE32BB64C&, GetOEMIDList("S.BERMAN", "English")},
            {&H7BC949F3&, GetOEMIDList("T V2.11 ", "English")},
            {&HC1C6ECB8&, GetOEMIDList("T V4.00 ", "English")},
            {&H577983D2&, GetOEMIDList("TAN  3.2", "English")},
            {&H847631E8&, GetOEMIDList("TAN  3.3", "English")},
            {&HC82880D8&, GetOEMIDList("TAN  3.3", "English")},
            {&H69B1B489&, GetOEMIDList("Tandy557", "English")},
            {&HA26247F1&, GetOEMIDList("TracerST", "English")},
            {&HCA33CAD&, GetOEMIDList("VGACPY51", "English")},
            {&H1F29F8C6&, GetOEMIDList("VGACP625", "English")},
            {&HB9067457&, GetOEMIDList("WINIMAGE", "English")},
            {&H78E72263&, GetOEMIDList("WINIMAGE", "English")},
            {&HCB438B3C&, GetOEMIDList("XTF-BOOT", "English")},
            {&H7E03A60A&, GetOEMIDList("XTREEWIN", "English")}
        }

        Return Result
    End Function
    Private Function GetOEMIDList(OEMID As String, Language As String) As OEMIDList
        Dim BootstrapType As New OEMIDList
        With BootstrapType
            .OEMIDList = Split(OEMID, ",").ToList
            .Language = Language
        End With

        Return BootstrapType
    End Function
End Module
Public Class OEMIDList
    Public OEMIDList As List(Of String)
    Public Language As String
End Class
