name: Discord Webhook Debug

on:
  workflow_dispatch: {}

jobs:
  ping:
    runs-on: ubuntu-latest
    env:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
    steps:
      - name: Sanity ping (plain text)
        run: |
          echo "Posting a simple message to verify the webhook/channel…"
          # Capture HTTP code and response
          CODE=$(curl -sS -o /tmp/resp.txt -w '%{http_code}' \
            -H "Content-Type: application/json" \
            -d '{"content":"✅ Webhook test from GitHub Actions."}' \
            "${DISCORD_WEBHOOK}")
          echo "HTTP: $CODE"
          echo "Response:"
          cat /tmp/resp.txt
          # 204 = success (Discord webhooks return 204 No Content on success)
          if [ "$CODE" -ne 204 ]; then
            echo "::error::Discord did not accept the message (HTTP $CODE)"
            exit 1
          fi

      - name: Install jq
        run: |
          sudo apt-get update -y >/dev/null 2>&1
          sudo apt-get install -y jq >/dev/null 2>&1

      - name: Post a sample embed (robust JSON escaping)
        env:
          REPO_NAME: ${{ github.repository }}
        run: |
          SAMPLE_BODY="This is a test embed description.\n• Supports **Markdown**\n• Shows up if JSON is valid"
          # Truncate to 4096 (embed description limit)
          BODY_TRUNCATED=$(printf '%s' "$SAMPLE_BODY" | head -c 4096)
          # Encode as JSON string safely
          BODY_JSON=$(printf '%s' "$BODY_TRUNCATED" | jq -Rs .)

          payload=$(jq -n \
            --arg title "$REPO_NAME – Debug Embed" \
            --arg url "https://github.com/${REPO_NAME}" \
            --arg ts "$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
            --argjson desc "$BODY_JSON" '
            {
              embeds: [
                {
                  title: $title,
                  url: $url,
                  description: $desc,
                  timestamp: $ts,
                  footer: { text: "Webhook debug" }
                }
              ]
            }')

          CODE=$(curl -sS -o /tmp/resp2.txt -w '%{http_code}' \
            -H "Content-Type: application/json" \
            -d "$payload" \
            "${DISCORD_WEBHOOK}")
          echo "HTTP: $CODE"
          echo "Response:"
          cat /tmp/resp2.txt
          if [ "$CODE" -ne 204 ]; then
            echo "::error::Discord rejected the embed (HTTP $CODE)"
            exit 1
          fi
