name: Post release to Discord

on:
  release:
    types:
      - published

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    env:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      RELEASE_NAME: ${{ github.event.release.name }}
      RELEASE_TAG: ${{ github.event.release.tag_name }}
      RELEASE_URL: ${{ github.event.release.html_url }}
      RELEASE_BODY: ${{ github.event.release.body }}
      REPO_NAME: ${{ github.repository }}
      AUTHOR: ${{ github.event.release.author.login }}
    steps:
      - name: Post to Discord
        shell: bash
        run: |
          # Truncate to Discord embed description limit (4096 chars)
          if [ "${#RELEASE_BODY}" -gt 4096 ]; then
            BODY_TRUNCATED="${RELEASE_BODY:0:4095}…"
          else
            BODY_TRUNCATED="$RELEASE_BODY"
          fi

          # Build the JSON payload (simple embed)
          payload=$(cat <<JSON
          {
            "embeds": [
              {
                "title": "${REPO_NAME} – ${RELEASE_NAME} (${RELEASE_TAG})",
                "url": "${RELEASE_URL}",
                "description": ${BODY_TRUNCATED@Q},
                "timestamp": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
                "footer": { "text": "Released by ${AUTHOR}" }
              }
            ]
          }
          JSON
          )

          # Send to Discord
          curl -sS -X POST -H "Content-Type: application/json" \
            -d "$payload" "$DISCORD_WEBHOOK"
