// GitHub -> (your server) -> Discord
import express from "express";
import fetch from "node-fetch";

const app = express();
app.use(express.json({ type: ["application/json", "application/*+json"] }));

app.post("/github", async (req, res) => {
  if (req.header("X-GitHub-Event") !== "release") return res.sendStatus(204);
  const r = req.body.release;
  if (!r || req.body.action !== "published") return res.sendStatus(204);

  const desc = (r.body || "");
  const description = desc.length > 4096 ? desc.slice(0, 4095) + "…" : desc;

  const payload = {
    embeds: [{
      title: `${req.body.repository.full_name} – ${r.name} (${r.tag_name})`,
      url: r.html_url,
      description,
      timestamp: new Date().toISOString(),
      footer: { text: `Released by ${r.author?.login || "unknown"}` }
    }]
  };

  await fetch(process.env.DISCORD_WEBHOOK, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(payload)
  });

  res.sendStatus(200);
});

app.listen(3000, () => console.log("listening on :3000"));
